---
hero_image: images/banner.png
listed: true
copyedit: false
title: Tech speelgoed
description: Leer hoe je je eigen tech speelgoed kunt coderen!
version: 4
last_tested: 2019-04-10
steps:
  - 
    title: Inleiding
  - 
    title: Draaiende vlinderdas
  - 
    title: 'Uitdaging: van kleur veranderende zonnebril'
    challenge: true
  - 
    title: Je helikopter inschakelen
  - 
    title: Met je helikopter vliegen
  - 
    title: Loopings
  - 
    title: 'Uitdaging: maak je eigen tech speelgoed!'
    challenge: true
  - 
    title: Wat kun je verder nog doen?
