---
hero_image: images/banner.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Tech Toys
description: Learn how to code your own tech toys!
original_url: https://codeclubprojects.org/en-GB/scratch/tech-toys
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Spinning Bow Tie
- title: 'Challenge: Colour-changing sunglasses'
- title: Powering up your helicopter
- title: Flying your helicopter
- title: 'Challenge: More controls'
- title: Loop-the-loop
- title: 'Challenge: Create your own tech toy!'