---
hero_image: images/banner.png
listed: true
copyedit: false
title: Technik Spielzeug
description: Lerne wie du dein eigenes Technik Spielzeug programmierst!
version: 4
last_tested: 2019-04-10
steps:
- title: Einleitung
  completion: engaged
- title: Rotierende Fliege
- title: 'Herausforderung: Farbwechselnde Sonnenbrille'
  challenge: true
- title: Starte deinen Hubschrauber
- title: Fliege deinen Hubschrauber
  completion: internal
- title: Looping
- title: 'Herausforderung: Erstelle dein eigenes Technik-Spielzeug!'
  challenge: true
- title: Wie geht''s weiter?
