---
hero_image: images/banner.png
listed: true
copyedit: false
title: Technikspielzeug
description: Lerne wie du dein eigenes Technikspielzeug programmierst!
version: 4
last_tested: 2019-04-10
steps:
  - 
    title: Einleitung
  - 
    title: Rotierende Fliege
  - 
    title: 'Herausforderung: Farbwechselnde Sonnenbrille'
    challenge: true
  - 
    title: Starte deinen Hubschrauber
    completion:
      - engaged
  - 
    title: Fliege deinen Hubschrauber
  - 
    title: Looping
    completion:
      - internal
  - 
    title: 'Herausforderung: Erstelle dein eigenes Technikspielzeug!'
    challenge: true
  - 
    title: Wie geht es weiter?
