---
hero_image: images/banner.png
listed: true
copyedit: false
title: Jouets technologiques
description: Apprends à coder tes propres jouets technologiques!
version: 4
last_tested: 2019-04-10
steps:
- title: Introduction
  completion: engaged
- title: Nœud papillon tournant
- title: 'Défi: lunettes de soleil à couleurs changeantes'
  challenge: true
- title: Mettre ton hélicoptère sous tension
- title: Faire voler ton hélicoptère
  completion: internal
- title: Faire un looping
- title: 'Défi: créer ton propre jouet technologique!'
  challenge: true
- title: Et ensuite?
